homepage: "https://github.com/apache/commons-validator"
language: jvm
primary_contact: "irali@google.com"
main_repo: "https://github.com/apache/commons-validator.git"
file_github_issue: false
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
