homepage: "https://www.mongodb.com/"
language: c++
primary_contact: "mongo-c-driver-ossfuzz@mongodb.com"
auto_ccs:
 - "david@adalogics.com"
 - "kevin.albertson@mongodb.com"
 - "clyde.bazile@mongodb.com"
 - "samantha.ritter@mongodb.com"
 - "roberto.sanchez@mongodb.com"
main_repo: "https://github.com/mongodb"
