homepage: "https://www.hdfgroup.org/solutions/hdf5/"
main_repo: "https://github.com/HDFGroup/hdf5"
language: c
primary_contact: "derobins@hdfgroup.org"
vendor_ccs:
  - "Adam@adalogics.com"
  - "David@adalogics.com"
  - "jhenderson@hdfgroup.org"
  - "nfortne2@hdfgroup.org"
sanitizers:
  - address
  - undefined
  - memory
