homepage: "https://gitlab.com/cryptsetup/cryptsetup"
language: c
builds_per_day: 2
primary_contact: "gmazyland@gmail.com"
auto_ccs:
  - okozina@redhat.com
  - vtrefny@redhat.com
  - daniel.zatovic@gmail.com
sanitizers:
  - address
  # - memory ## msan disabled after a clang bump. Please re-enable it, Try to fix any build warnings and build errors, as well as msan runtime warnings and errors. msan failure log: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-bf77a9dc-080e-4e3b-ba89-cbaf65a54e61.txt
  - undefined
architectures:
  - x86_64
main_repo: "https://gitlab.com/cryptsetup/cryptsetup.git"

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

