homepage: "https://github.com/google/skia"
language: c++
primary_contact: "kjlubick@chromium.org"
auto_ccs:
  - "hcm@google.com"
  - "brianosman@google.com"
  - "johnstiles@google.com"
  - "robertphillips@google.com"
  - "egdaniel@google.com"
  - "skia-gpu-wrangler@google.com"
  - "skia-bugs-central@skia-public.iam.gserviceaccount.com"
  - "fuzz@skia.org"
  - "armansito@google.com"
  - "drott@chromium.org"
  - "jvanverth@google.com"
vendor_ccs:
  - "lsalzman@mozilla.com"
  - "twsmith@mozilla.com"
sanitizers:
 - address
 - undefined
 # - memory ## msan disabled after a clang bump. Please re-enable it, Try to fix any build warnings and build errors, as well as msan runtime warnings and errors. msan failure log: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-8aacfca6-c946-4753-a977-d836fc3e334f.txt
help_url: "https://skia.org/docs/dev/testing/fuzz/"
builds_per_day: 4
main_repo: 'https://skia.googlesource.com/skia.git'
