homepage: "http://freeimage.sourceforge.net/"
primary_contact: "kusano@google.com"

experimental: true

sanitizers:
  - address
  - memory
  - undefined

labels:
  load_from_memory_fuzzer:
    - sundew
