homepage: "http://www.leptonica.com"
primary_contact: "taking@google.com"
auto_ccs:
  - "kusano@google.com"
sanitizers:
  - address
  - undefined
  - memory
experimental: True
labels:
  pix_rotate_shear_fuzzer:
    - sundew
