homepage: "https://gitlab.isc.org/isc-projects/bind9"
language: c
primary_contact: "security-officer@isc.org"
auto_ccs:
  - "ondrej@sury.org"
  - "michal@isc.org"
fuzzing_engines:
  - libfuzzer
  - honggfuzz
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
