homepage: "https://gitlab.isc.org/isc-projects/bind9"
language: c
primary_contact: "security-officer@isc.org"
auto_ccs:
  - "ondrej@isc.org"
  - "michal@isc.org"
  - "marka@isc.org"
  - "wpk@isc.org"
  - "matthijs@isc.org"
  - "dfronza@isc.org"
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
