homepage: "https://www.libressl.org/"
primary_contact: "libressl-fuzzing@openbsd.org"
auto_ccs:
 - "busterb@gmail.com"
 - "miwaxe@gmail.com"
sanitizers:
 - address
 - memory:
    experimental: True
 - undefined
