homepage: "https://samba.org"
primary_contact: "douglas.bagnall@catalyst.net.nz"
auto_ccs:
  - "abartlet+google@catalyst.net.nz"
  - "cryptomilk@gmail.com"
sanitizers:
  - address
  - undefined
help_url: "https://wiki.samba.org/index.php/Fuzzing"
