homepage: "https://sleuthkit.org"
language: c++
primary_contact: "carrier@sleuthkit.org"
auto_ccs:
 - "simsong@gmail.com"
main_repo: 'https://github.com/sleuthkit/sleuthkit'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

