homepage: "https://github.com/istio/istio"
primary_contact: "istio-security-vulnerability-reports@googlegroups.com"
auto_ccs :
  - "adam@adalogics.com"
  - "howardjohn@google.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
