homepage: "https://xiph.org/vorbis/"
language: c++
primary_contact: "daede003@umn.edu"
auto_ccs:
  - "le.businessman@gmail.com"
  - "paul.l.kehrer@gmail.com"
vendor_ccs:
  - "twsmith@mozilla.com"
sanitizers:
  - address
  - memory
  - undefined
