homepage: "https://github.com/facebook/proxygen"
primary_contact: "mhl@fb.com"
auto_ccs:
  - "gulshan@fb.com"
  - "reed@fb.com"
  - "lniccolini@fb.com"
vendor_ccs:
  - "oss-fuzz@fb.com"
sanitizers:
  - address
  - undefined
