homepage: https://github.com/Yubico/libfido2
language: c++
primary_contact: "kostas@yubico.com"
auto_ccs:
    - "pedro@ambientworks.net"
    - "marissa.nishimoto@yubico.com"
    - "pedro.ossfuzz@gmail.com"
    - "ludvig.michaelsson@yubico.com"
    - "alex.geana@yubico.com"
sanitizers:
    - address
    - undefined
    # - memory ## msan disabled after a clang bump. Please re-enable it, Try to fix any build warnings and build errors, as well as msan runtime warnings and errors. msan failure log: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-64f6f45d-a700-42a0-9675-31f43e230e10.txt
fuzzing_engines:
    - libfuzzer
    - honggfuzz
    - afl
    # - centipede disabled due to https://github.com/google/oss-fuzz/pull/10248#issuecomment-1579657163
main_repo: 'https://github.com/Yubico/libfido2'
