homepage: "https://pygments.org/"
main_repo: "https://github.com/pygments/pygments"
language: python
primary_contact: "security-tps@google.com"
auto_ccs:
  - "jvoisin@google.com"
  - "ipudney@google.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
