homepage: "https://github.com/seladb/PcapPlusPlus"
language: c++
primary_contact: "pcapplusplus@gmail.com"
auto_ccs:
  - "zlowram@gmail.com"
  - "aleksandrosansan@gmail.com"
  - "peron.clem@gmail.com"
  - "egecetin97@gmail.com"
fuzzing_engines:
  - afl
  - libfuzzer
sanitizers:
  - address
  # - memory ## msan disabled after a clang bump. Please re-enable it, Try to fix any build warnings and build errors, as well as msan runtime warnings and errors. msan failure log: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-1f13ef0f-0037-49c3-8d80-9b784f8f7589.txt
  - undefined
main_repo: 'https://github.com/seladb/PcapPlusPlus'
coverage_extra_args: -ignore-filename-regex=/libpcap/ -ignore-filename-regex=/PcapPlusPlus/3rdParty/
