homepage: "https://opencv.org/"
primary_contact: "kusano@google.com"

experimental: true

auto_ccs:
  - "vrabaud@google.com"

sanitizers:
  - address
  - undefined
  - memory

labels:
  imdecode_fuzzer:
    - sundew
  imread_fuzzer:
    - sundew
