homepage: "http://www.graphicsmagick.org/"
main_repo: "https://github.com/kstep/graphicsmagick"
language: c++
primary_contact: "bobjfriesenhahn@gmail.com"
auto_ccs:
    - troyjp@gmail.com
    - alex.gaynor@gmail.com
    - paul.l.kehrer@gmail.com
sanitizers:
    - address
    # - memory ## msan disabled after a clang bump. Please re-enable it, Try to fix any build warnings and build errors, as well as msan runtime warnings and errors. msan failure log: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-17b7b4f4-53de-4bd7-878c-d1240f276016.txt
# Disabled MSAN because of https://github.com/google/oss-fuzz/issues/6294
# # - memory ## msan disabled after a clang bump. Please re-enable it, Try to fix any build warnings and build errors, as well as msan runtime warnings and errors. msan failure log: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-17b7b4f4-53de-4bd7-878c-d1240f276016.txt
architectures:
    - x86_64
    - i386
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - afl
