homepage: "https://hunspell.github.io/"
language: c++
primary_contact: "caolanm@gmail.com"
vendor_ccs:
  - "twsmith@mozilla.com"
sanitizers:
  - address
  # - memory ## msan disabled after a clang bump. Please re-enable it, Try to fix any build warnings and build errors, as well as msan runtime warnings and errors. msan failure log: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-46e640a5-de1c-4dcf-9812-d4f69c75dbbb.txt
  - undefined
architectures:
  - i386
  - x86_64
main_repo: 'https://github.com/hunspell/hunspell.git'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

