homepage: "https://hunspell.github.io/"
primary_contact: "caolanm@redhat.com"
auto_ccs:
  - "security@documentfoundation.org"
vendor_ccs:
  - "eakhgari@mozilla.com"
  - "twsmith@mozilla.com"
sanitizers:
  - address
  - memory
  - undefined
architectures:
 - i386
 - x86_64
