homepage: "https://xz.tukaani.org/xz-utils/"
language: c++
primary_contact: "lasse.collin@tukaani.org"
auto_ccs:
  - "bshas3@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/tukaani-project/xz.git'
