homepage: "https://opensource.zalando.com/skipper/"
primary_contact: "sandor.szuecs@zalando.de"
auto_ccs:
  - "oss-fuzz+team-gwproxy@zalando.de"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/zalando/skipper"
