homepage: "http://llvm.org/"
language: c++
primary_contact: "kcc@google.com"
auto_ccs:
  - "mascasa@google.com"
  - "jonas@devlieghere.com"
  - "vsk@apple.com"
  - "akilsrin@apple.com"
  - "llvm-bugs@lists.llvm.org"
  - "igmyrj@gmail.com"
  - "mitchphillips@outlook.com"
  - "mitchp@google.com"
  - "xpl0re@gmail.com"
  - "jfb@chromium.org"
  - "eneyman@google.com"
  - "bigcheesegs@gmail.com"
  - "davg@google.com"
  - "sammccall@google.com"
  - "david@adalogics.com"

sanitizers:
  - address
#  - memory ## msan disabled after a clang bump. Please re-enable it, Try to fix any build warnings and build errors, as well as msan runtime warnings and errors. msan failure log: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-a3d59d5e-8ae4-4294-9a84-bed1f85c2923.txt

fuzzing_engines:
  - libfuzzer
  - honggfuzz

# Bug reports are public by default:
view_restrictions: none
main_repo: 'https://github.com/llvm/llvm-project.git'
