homepage: "https://github.com/bytecodealliance/wasm-micro-runtime"
language: c
primary_contact: "liang.he@intel.com"
auto_ccs:
  - "wenyong.huang@intel.com"
  - "tianlong.liang@intel.com"
main_repo: "https://github.com/bytecodealliance/wasm-micro-runtime.git"
sanitizers:
  - address
  - memory
  - undefined
fuzzing_engines:
  - libfuzzer
file_github_issue: true
