homepage: "http://www.bzip.org/"
primary_contact: "jseward@acm.org"
auto_ccs:
  - "bshas3@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - dataflow
sanitizers:
  - address
  - dataflow
  - memory
