homepage: "https://github.com/OpenNavigationSurface/BAG"
language: c++
primary_contact: "selimnairb@gmail.com"
auto_ccs:
  - "bmiles@ccom.unh.edu"
  - "brc@ccom.unh.edu"
  - "glen.rice@noaa.gov"
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
main_repo: 'https://github.com/OpenNavigationSurface/BAG.git'
