homepage: "https://opus-codec.org/"
language: c++
primary_contact: "jmvalin@jmvalin.ca"
auto_ccs:
  - "flim@google.com"
vendor_ccs:
  - "twsmith@mozilla.com"
sanitizers:
  - address
  - memory
  - undefined
