homepage: "https://speex.org/"
language: c++
primary_contact: "tmatth@videolan.org"
auto_ccs:
  - "twsmith@mozilla.com"
  - "le.businessman@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
