homepage: "https://github.com/google/jsonnet"
primary_contact: "dcunnin@google.com"
auto_ccs:
  - "wwweiwang@google.com"

sanitizers:
  - address
  - memory
  - undefined

labels:
  convert_jsonnet_fuzzer:
    - sundew
