homepage: "https://github.com/nlohmann/json"
language: c++
primary_contact: "niels.lohmann@gmail.com"
auto_ccs:
  - "tanujgarg@google.com"
sanitizers:
 - address
 - undefined
 # - memory ## msan disabled after a clang bump. Please re-enable it, Try to fix any build warnings and build errors, as well as msan runtime warnings and errors. msan failure log: https://oss-fuzz-gcb-logs.storage.googleapis.com/log-2934fed0-ecd0-4bd9-800d-872b35e844e9.txt
main_repo: 'https://github.com/nlohmann/json.git'

fuzzing_engines:
  - afl
  - honggfuzz
  - libfuzzer

