homepage: "https://www.ffmpeg.org/"
primary_contact: "ffmpeg-security@ffmpeg.org"
auto_ccs:
 - "michaelni@gmx.at"
 - "jrummell@google.com"
 - "tfoucu@google.com"
 - "cdiehl@mozilla.com"
 - "kempfjb@gmail.com"
selective_unpack: true
