homepage: "https://github.com/google/syzkaller.git"
primary_contact: "dvyukov@google.com"
auto_ccs:
  - "andreyknvl@google.com"
  - "mmoroz@chromium.org"
  - "syzkaller@googlegroups.com"
sanitizers:
  - address
view_restrictions: none
