homepage: "http://qpdf.sourceforge.net/"
primary_contact: "taking@google.com"
auto_ccs:
  - "qberkenbilt@gmail.com"

sanitizers:
  - address
  - undefined
  - memory

labels:
  qpdf_read_memory_fuzzer:
    - sundew
