homepage: "http://www.littlecms.com/"
language: c++
primary_contact: "marti.maria.s@gmail.com"
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
architectures:
  - x86_64
  - i386
