homepage: "https://github.com/mpv-player/mpv"
language: c
primary_contact: "kasper93@gmail.com"
architectures:
 - x86_64
 - i386
sanitizers:
  - address
  - undefined
main_repo: 'https://github.com/mpv-player/mpv'
